### ISSUE TITLE
Gem Load Error is: undefined method `register' for Inliner:Class

### ISSUE THREAD

**Issue by gawin** [kaiinui/middleman-inliner#17]
Gem Load Error is: undefined method `register' for Inliner:Class

```
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'middleman-inliner'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `register' for Inliner:Class
Backtrace for gem load error is:
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-inliner-1.0.1/lib/middleman-inliner.rb:43:in `<top (required)>'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
/usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:10:in `<top (required)>'
/usr/local/var/rbenv/versions/2.4.0/bin/middleman:22:in `load'
/usr/local/var/rbenv/versions/2.4.0/bin/middleman:22:in `<main>'
Bundler Error Backtrace:
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
	from /usr/local/var/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:10:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.4.0/bin/middleman:22:in `load'
	from /usr/local/var/rbenv/versions/2.4.0/bin/middleman:22:in `<main>'
```

**Comment by gawin** [comment]
Fixed it with these two changes in `lib/middleman-inliner.rb`

1. Comment out the `compass config`:
```ruby
# app.compass_config do |config|
#   config.output_style = :compressed
# end
```
2. Update how the extension is registered:
```ruby
# Inliner.register(:inliner)
::Middleman::Extensions.register(:inliner, Inliner)
```

**Comment by elliotec** [comment]
@gawin solution worked for me. Too bad it isn't being accepted as a pull request. Perhaps a fork may be warranted here. Thank you!

**Comment by ariffmunshi** [comment]
Been getting a similar error.

```
11:35:21 AM: Executing user command: middleman build
11:35:21 AM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'middleman-inliner'. (Bundler::GemRequireError)
11:35:21 AM: Gem Load Error is: undefined method `register' for Inliner:Class
11:35:21 AM: Backtrace for gem load error is:
11:35:21 AM: /opt/build/cache/bundle/ruby/2.3.0/gems/middleman-inliner-1.0.1/lib/middleman-inliner.rb:43:in `<top (required)>'
11:35:21 AM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
11:35:21 AM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
11:35:21 AM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
11:35:21 AM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
11:35:21 AM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
11:35:21 AM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
11:35:21 AM: /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
11:35:22 AM: /opt/build/cache/bundle/ruby/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
11:35:22 AM: /opt/build/cache/bundle/ruby/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
11:35:22 AM: /opt/build/cache/bundle/ruby/2.3.0/gems/middleman-cli-4.2.1/bin/middleman:10:in `<top (required)>'
11:35:22 AM: /opt/build/cache/binstubs/middleman:29:in `load'
11:35:22 AM: /opt/build/cache/binstubs/middleman:29:in `<main>'
11:35:22 AM: Bundler Error Backtrace:
11:35:22 AM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
11:35:22 AM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
11:35:22 AM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
11:35:22 AM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
11:35:22 AM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
11:35:22 AM: 	from /opt/buildhome/.rvm/gems/ruby-2.3.6/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
11:35:22 AM: 	from /opt/build/cache/bundle/ruby/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:35:in `setup_bundler'
11:35:22 AM: 	from /opt/build/cache/bundle/ruby/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
11:35:22 AM: 	from /opt/build/cache/bundle/ruby/2.3.0/gems/middleman-cli-4.2.1/bin/middleman:10:in `<top (required)>'
11:35:22 AM: 	from /opt/build/cache/binstubs/middleman:29:in `load'
11:35:22 AM: 	from /opt/build/cache/binstubs/middleman:29:in `<main>'
```

Edited the files but can't seem to build in production still.
