### ISSUE TITLE
compatibility with middleman v4.0.0.beta.2?

### ISSUE THREAD

**Issue by mrtnpro** [kaiinui/middleman-inliner#9]
When using this gem with middleman v4 I get the following error. 

``` ruby
/Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/middleman-inliner-1.0.1/lib/middleman-inliner.rb:43:in `<top (required)>': undefined method `register' for Inliner:Class (NoMethodError)
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:76:in `require'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:72:in `each'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:72:in `block in require'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:61:in `each'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.3/lib/bundler/runtime.rb:61:in `require'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.3/lib/bundler.rb:134:in `require'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/middleman-core-4.0.0.beta.2/lib/middleman-core/load_paths.rb:33:in `setup_bundler'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/middleman-core-4.0.0.beta.2/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
    from /Users/martin/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/middleman-cli-4.0.0.beta.2/bin/middleman:10:in `<top (required)>'
    from /Users/martin/.rbenv/versions/2.1.6/bin/middleman:23:in `load'
    from /Users/martin/.rbenv/versions/2.1.6/bin/middleman:23:in `<main>'
```

This extension is pretty awesome if you are concerned about critical-path loading (as I am). My current workaround for inlining styles or javascripts is:

``` slim
javascript:
  #{ File.read( File.expand_path("source/javascripts/foobar.js") )}
```

…which obviously isn't a very durable solution. Therefore having a working extension that provides me a helper tag would be awesome <3.

**Comment by thoughtandtheory** [comment]
Do you have a similar workaround for inlining stylesheets? Specially trying to get it to read a sass file that compiles everything.

**Comment by mrtnpro** [comment]
@thoughtandtheory 

You might try this:

``` slim
sass:
  #{ File.read( File.expand_path("source/stylesheets/foobar.sass") )}
```
